//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Requisition.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ExcelExportEntities : DbContext
    {
        public ExcelExportEntities()
            : base("name=ExcelExportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Floor> Floor { get; set; }
        public virtual DbSet<Requisition> Requisition { get; set; }
        public virtual DbSet<Requisition_Event> Requisition_Event { get; set; }
        public virtual DbSet<Requisition_State> Requisition_State { get; set; }
        public virtual DbSet<ReturnReason> ReturnReason { get; set; }
        public virtual DbSet<ScrappedDetail> ScrappedDetail { get; set; }
        public virtual DbSet<Unit> Unit { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<User_Notification> User_Notification { get; set; }
        public virtual DbSet<User_Profile> User_Profile { get; set; }
        public virtual DbSet<User_Profile_REF> User_Profile_REF { get; set; }
    }
}
