//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Requisition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisition_Event
    {
        public int id { get; set; }
        public int requisition_id { get; set; }
        public int user_id { get; set; }
        public int requisition_state_id { get; set; }
        public System.DateTime modified_date { get; set; }
        public string remark { get; set; }
    
        public virtual Requisition Requisition { get; set; }
        public virtual Requisition_State Requisition_State { get; set; }
        public virtual User User { get; set; }
    }
}
