//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_Requisition.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScrappedDetail
    {
        public int id { get; set; }
        public Nullable<System.DateTime> createDate { get; set; }
        public string po { get; set; }
        public string modelName { get; set; }
        public string materialNumber { get; set; }
        public Nullable<int> amount { get; set; }
        public string reason { get; set; }
        public string kind { get; set; }
        public Nullable<int> price { get; set; }
        public string negligenceUser { get; set; }
        public string remark { get; set; }
        public int floor_id { get; set; }
    
        public virtual Floor Floor { get; set; }
    }
}
